#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running ESLint..."
cd eslint-enabler
npm run lint
npm run prettier
if [ $? -ne 0 ]; then
  echo "Linting failed. Commit aborted."
  exit 1
fi
echo "Linting successful. Proceeding with commit."

